- name: Install catalogue component
  hosts: catalogue
  become: yes
  tasks: 
  - name: Setup npm source
    tags:
    - installation
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install NodeJS
    tags:
    - installation
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: check whether the roboshop user exists or not
    tags:
    - installation
    ansible.builtin.command: id roboshop
    register: output # output is variable name
    ignore_errors: true

  - when: output.rc != 0  
    name: create user roboshop
    tags:
    - installation
    become: yes # we need sudo access for this task only
    ansible.builtin.user:
      name: roboshop
  
  - name: Check whether /app directory exists or not
    tags:
    - installation
    ansible.builtin.stat:
      path: /app
    register: directory

  - name: print the directory stats
    tags:
    - installation
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: Create /app directory
    tags:
    - installation
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download catalogue artifact
    tags:
    - deployment
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: Extract catalogue artifact
    tags:
    - deployment
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    tags:
    - deployment
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy Catalogue service
    tags:
    - installation
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload
    tags:
    - installation
    ansible.builtin.systemd:
      daemon_reload: true

  - name: copy mongo repo to yum.repos.d
    tags:
    - installation
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB
    tags:
    - installation
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: Load catalogue data
    tags:
    - installation
    ansible.builtin.command: mongo --host mongodb.practicedevops.shop < /app/schema/catalogue.js

  - name: Restart Catalogue
    tags:
    - deployment
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: true
