- name: DEMO on Filters
  hosts: localhost
  vars:
    NAME: Veera
  tasks: 
  - name: convert into upper case
    debug:
      msg: "Hello {{ NAME | upper }}"

  - name: printing undefined variables
    debug:
      msg: "Course is {{ COURSE | default('DevOps') }}"