- name: DEMO on Filters
  hosts: localhost
  vars:
    NAME: Veera
    website: https://www.joindevops.com/batch-74s
    Greeting: Hello Venky, How are you 
  tasks: 
  - name: convert into upper case
    debug:
      msg: "Hello {{ NAME | upper }}"

  - name: printing undefined variables
    debug:
      msg: "Course is {{ COURSE | default('DevOps') }}"

  - name: extract hostname
    debug:
      msg: "{{ website | urlsplit('hostname') }}"

  - name: split
    debug:
      msg: "{{ Greeting | split(',')}}"
